apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mohammed-005/devops-capstone-app.git'
    targetRevision: HEAD
    path: helm/capstone-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true