replicaCount: 2

image:
  repository: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/devops-capstone-app
  tag: "4e599668b936a16b902c10c4155b750a2798e286"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: aws-ecr-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

